build: "build/*"
ci: "ci/*"
docs: "docs/*"
feat: "feat/*"
fix: "fix/*"
perf: "perf/*"
refactor: "refactor/*"
style: "style/*"
test: "test/*"
other: "other/*"
dependency: "dependency/*"
release: "release/*"