[build-system]
    build-backend = "setuptools.build_meta"
    requires = ["setuptools>=65.5", "wheel"]

[project]
    authors = [
        {email = "vagabondHustler.github@gmail.com"},
        {name = "vagabondHustler"},
    ]
    classifiers = [
        "Intended Audience :: Developers",
        "Intended Audience :: End Users/Desktop",
        "Operating System :: Microsoft :: Windows",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Multimedia :: Video",
        "Topic :: Utilities",
    ]
    dependencies = [
        "picologging==0.9.3",
        "cloudscraper==1.2.71",
        "num2words==0.5.13",
        "packaging==23.2",
        "pillow==10.2.0",
        "pystray==0.19.5",
        "requests==2.31.0",
        "selectolax==0.3.20",
        "toml==0.10.2",
    ]
    description = "Subsearch"
    dynamic = ["version"]
    keywords = [
        "subtitles",
        "sub",
        "srt",
        "tool",
        "tools",
        "download",
        "movies",
        "shows",
        "scrape",
        "opensubtitles",
        "subscene",
        "subsearch",
        "subtitles",
        "yifysubtitles",
    ]
    license = {text = "MIT license"}
    name = "Subsearch"
    readme = "README.md"
    requires-python = ">=3.10"

[project.urls]
    repository = "https://github.com/vagabondHustler/subsearch"

[project.scripts]
    subsearch = "subsearch:main"

[tool.setuptools]
    platforms = ["win32"]
    zip-safe = false

[tool.setuptools.packages.find]
    exclude = ["examples*", "subsearch.test*", "tools*"]
    include = ["subsearch*"]
    where = ["src"]

[tool.setuptools.dynamic]
    version = {attr = "subsearch.data.__version__"}

[project.optional-dependencies]
    build = [
        # until cx_Freeze supports Python 3.12 on windows, use:
        # pip install --force --no-cache --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze
        # https://github.com/marcelotduarte/cx_Freeze/issues/2153
        "build==1.1.1",
        "twine==5.0.0",
        "psutil==5.9.8",
    ]
    lint = ["black==24.2.0", "isort==5.13.2"]
    tests = [
        "pytest-cov==4.1.0",
        "pytest==8.0.2",
        "tox==4.13.0",
        "python-dotenv==1.0.1",
    ]
    tools = ["pyperclip==1.8.2"]
    type = ["mypy==1.8.0"]

[tool.pytest.ini_options]
    addopts = "--cov=src/subsearch"
    filterwarnings = ['ignore::DeprecationWarning']
    log_cli = true
    log_cli_level = 'DEBUG'
    testpaths = ["tests"]

[tool.black]
    line-length = 120

[tool.isort]
    profile = "black"
    skip = ".gitignore"
    extend_skip = [".md", ".json", ".yml", ".toml"]
    line_length = 120


[tool.mypy]
    check_untyped_defs = true
    ignore_missing_imports = true
    mypy_path = ["src", "tests", "tools"]
    warn_no_return = false
