[build-system]
requires = ["setuptools>=63.2", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--cov=subsearch"
testpaths = [
    "tests",
]

[tool.black]
line-length = 125

[tool.isort]
profile = "black"
