[build-system]
requires = ["setuptools>=63.0", "beautifulsoup4>=4.11.1", "cloudscraper>=1.2.60", "num2words>=0.5.11", "requests>=2.28.1", "lxml>=4.9.1", "sv-ttk>=1.0", "wheel"]

build-backend = "setuptools.build_meta"