[build-system]
requires = ["setuptools>=63.2", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
filterwarnings =[
    'ignore::DeprecationWarning'
]
log_cli = true
log_cli_level = 'DEBUG'
addopts = "--cov=src/subsearch"
testpaths = [
    "tests",
]

[tool.black]
line-length = 125

[tool.isort]
profile = "black"

[tool.mypy]
mypy_path = "src"
ignore_missing_imports = true
warn_no_return = false 
