  name: Build and publish

  on:
    push:
      tags:
        - "v*.*.*"

  jobs:
    # build and publish release with pushed tags as release name
    build-and-publish:
      name: Build and publish
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v3
          with:
            ref: main
        - uses: actions/setup-python@v4
          with:
            python-version: "3.10.*"
        # install pyinstaller and requirements
        - name: Initializing
          run: |
            python -m pip install --upgrade pip
            pip install pyinstaller
            pip install -r docs/requirements.txt
        # copy source code to workflows
        - name: Copy source to .github/workflows/subsearch
          run: |
            cp -r ./src/subsearch/ .github/workflows/subsearch/
            rm .github\workflows\subsearch\__init__.py
            rm .github\workflows\subsearch\__main__.py
        # build the executable and manually add sv_ttk otherwise it wont be included
        - name: Build executable
          run: |
            pyinstaller .github/workflows/build.spec -y --clean --distpath ./SubSearch-x64
            cp -r C:/hostedtoolcache/windows/Python/3.10.5/x64/lib/site-packages/sv_ttk/ ./SubSearch-x64/SubSearch/sv_ttk
        # make archives for publishing
        - name: Make archives
          run: |
            python .github/workflows/_make_archive.py
            mv ./SubSearch-x64.zip ./SubSearch-${{ github.ref_name }}-win-x64.zip
            mv ./SubSearch-source.zip ./SubSearch-${{ github.ref_name }}-win-source.zip
        # publish the release with ACTION_TOKEN for verified release
        - name: Publish
          uses: softprops/action-gh-release@v1
          if: startsWith(github.ref, 'refs/tags/')
          with:
            token: ${{ secrets.ACTIONS_TOKEN }}
            generate_release_notes: True
            files: |
              SubSearch-${{ github.ref_name }}-win-x64.zip
              SubSearch-${{ github.ref_name }}-win-source.zip
