name: Continuous integration

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["3.10.*", "3.11.6"]
        
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            src:
              - 'src/**'

      - name: Set up Python ${{ matrix.python-version }}
        if: steps.changes.outputs.src == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        if: steps.changes.outputs.src == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Test with tox
        if: steps.changes.outputs.src == 'true'
        run: tox
