name: Continuous integration

on:
  pull_request:
    branches: ["main"]

jobs:
  check_changes:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check changes
        id: check_changes
        run: echo "changed_files=$(git diff --name-only ${{ github.event.after }} ${{ github.event.before }})" >> $GITHUB_ENV
        shell: bash
    outputs:
      changed_files: "${{ env.changed_files }}"

  test:
    needs: check_changes
    if: contains(needs.check_changes.outputs.changed_files, 'src/')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["3.10.*", "3.11.6"]
        
    steps:
      - uses: actions/checkout@v4
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Test with tox
        run: tox
