name: Lint

on:
  push:
    branches: ["main"]
    paths:
      - 'src/**'
      - 'scripts/**'
      - 'tests/**'

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Install black & isort
        run: |
          pip install black
          pip install isort
          isort ./src --profile 'black'
          black ./src -l 125
          isort ./tests --profile 'black'
          black ./tests -l 125
      - name: status, add, commit, fetch, push
        run: |
          git status
          git add -A
          git commit -S -m "format:: blacken"
          git fetch origin main
          git push origin HEAD:main
