name: Lint codebase
run-name: Lint codebase

on:
  push:
    branches:
      - main
    paths:
    - 'src/**'
    - 'scripts/**'
    - 'tests/**'


jobs:
  lint:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_config_global: true

      - name: Lint codebase
        run: |
          pip install black isort
          isort ./src ./tests --profile 'black'
          black ./src ./tests -l 125

      - name: Check for changes
        id: git_status
        run: |
          $gitStatus = git status --porcelain
          if ($gitStatus) {
              $changes="true"
          } else {
              $changes="false"
          }

      - name: Commit and push
        if: ${{ steps.git_status.outputs.changes == 'true' }}
        run: |
          git add -A
          git commit -S -m "Reformat codebase with black & isort"
          git fetch origin main
          git push origin HEAD:main
