# feat
name: Add labels & assignees to PR's

on:
  pull_request:
    types: [opened]
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Auto label
        uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/auto_label.yml
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

      - name: Auto assign
        uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: ".github/auto_assign.yml"
