name: Add labels & assignees to PR's

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr-labeler:
    if: ${{ contains(github.ref_name, 'feat/') || contains(github.ref_name, 'fix/') || contains(github.ref_name, 'chore/') || contains(github.ref_name, 'test/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Auto label
        uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/configs/auto_label.yml
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

      - name: Auto assign
        uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: .github/configs/auto_assign.yml
