name: Add labels & assignees to PR's

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Auto label
        if: ${{ contains(github.head_ref, 'feat') || contains(github.head_ref 'fix') || contains(github.head_ref 'chore') || contains(github.head_ref 'test') }}
        uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/configs/auto_label.yml
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

      - name: Auto assign
        uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: .github/configs/auto_assign.yml
