name: Add labels & assignees to PR's

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr-labeler:
    # if: ${{ contains(github.ref, 'feat') || contains(github.ref, 'fix') || contains(github.ref, 'chore') || contains(github.ref, 'test') }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${GITHUB_REF}
          echo ${GITHUB_HEAD_REF}
          echo ${GITHUB_REF_NAME}
          echo ${GITHUB_REF_TYP}
          echo ${GITHUB_PATH}
      - name: Auto label
        uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/configs/auto_label.yml
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

      - name: Auto assign
        uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: .github/configs/auto_assign.yml
