on:
  push:
    branches:
      - "dev*"

jobs:
  pr-other:
    if: |
      ${{ 
       (!startsWith(github.event.head_commit.message, 'Update')) && 
       (!startsWith(github.event.head_commit.message, 'Del')) &&
       (!startsWith(github.event.head_commit.message, 'Rename')) &&
       (!startsWith(github.event.head_commit.message, 'Move')) &&
       (!startsWith(github.event.head_commit.message, 'Docs')) &&
       (!startsWith(github.event.head_commit.message, 'Initial commit')) &&
       (!startsWith(github.event.head_commit.message, 'Reformat')) &&
       (!startsWith(github.event.head_commit.message, 'Tests'))
       }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull-request-other
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          pr_title: "Other | ${{ github.ref }}  into main"
          pr_body: "An automated PR"
          pr_assignee: "vagabondHustler"
          pr_label: "other"
          pr_draft: true
          pr_allow_empty: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

  pr-feature:
    if: ${{ !startsWith(github.event.head_commit.message, 'Feature') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull-request-feature
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          pr_title: "Features | ${{ github.ref }}  into main"
          pr_body: "An automated PR"
          pr_assignee: "vagabondHustler"
          pr_label: "feature"
          pr_draft: true
          pr_allow_empty: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

  pr-fix:
    if: ${{ !startsWith(github.event.head_commit.message, 'Fix') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull-request-fix
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          pr_title: "Fixes | ${{ github.ref }} into main"
          pr_body: "An automated PR"
          pr_assignee: "vagabondHustler"
          pr_label: "fix"
          pr_draft: true
          pr_allow_empty: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
