name: Add labels & assignees to PR's

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]

jobs:
  pr-labeler:
    if: ${{ startsWith(github.ref, 'feat') || startsWith(github.ref, 'fix') || startsWith(github.ref, 'chore') || startsWith(github.ref, 'test') }}
    runs-on: ubuntu-latest
    steps:
      - name: Auto label
        uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/configs/auto_label.yml
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

      - name: Auto assign
        uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: .github/configs/auto_assign.yml
