name: Sync branches
run-name: Sync branches

on:
  push:
    branches:
      - main

jobs:
  sync-branches:
    runs-on: windows-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4


      - name: Sync branches
        run: |
          git checkout main
          git push origin --delete dev
          git checkout -b dev
          git push origin dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}