name: Versioning

on:
  push:
    tags:
      - "*.*.*"

jobs:
  # get the current version, update version.json in ../data with new version with pushed tags
  semantic-versioning:
    name: Semantic versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10.*"
      # import GPG key for verified commits
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      # install jq to reading/writing .json files
      - name: Install jq
        run: sudo apt install jq
      # read version.json in ../data, save as variable version_output
      - name: Get current version
        id: current_version
        run: |
          echo "::set-output name=version_output::$(echo "`jq '.version' src/subsearch/data/version.json`")"
      # write pushed tags as version number into version.json in ../data
      - name: Set new version
        run: echo "`jq '.version="v${{ github.ref_name }}"' src/subsearch/data/version.json`" > src/subsearch/data/version.json
      - name: Update __version__.py
        run: python .github/workflows/_set__version__.py
      # commit version.json in ../data, with msg Bump version from vx.x.x to vx.x.x in /data
      - name: status, add, commit, fetch, push
        run: |
          git status
          git add src/subsearch/data/version.json
          git add src/subsearch/data/__version__.py
          git commit -S -m "Release: ${{steps.current_version.outputs.version_output}} -> v${{ github.ref_name }}"
          git fetch origin main
          git push origin HEAD:main
          git tag v${{ github.ref_name }}
          git push origin v${{ github.ref_name }}
          git push --delete origin ${{ github.ref_name }}
