name: Virustotal

on:
  release:
    types: [published]

jobs:
  virustotal:
    if: ${{ !endsWith(github.ref_name, '(rc|a|b)\\d+$') }}
    runs-on: ubuntu-latest
    steps:
      - name: Remove v from ${{ github.ref_name }}
        id: remove_v
        run: |
          v_version=${{ github.ref_name }}
          echo "current_version=${v_version:1}" >> $GITHUB_ENV

      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v3
        with:
          vt_api_key: ${{ secrets.VIRUSTOTAL_API_KEY }}
          github_token: ${{ secrets.ACTIONS_TOKEN }}
          update_release_body: false
          files: |
            Subsearch-${{ env.current_version }}-win64.msi
